In [1]:
import tensorflow as tf
import numpy as np

In [29]:
size = 3
batch_size = 1
img_batch = np.arange(size*size*batch_size,dtype=np.float32).reshape([batch_size,size,size,1]) #[batch_size, height, width, color]
img_batch.shape

(1, 3, 3, 1)

In [30]:
img_batch[0].T[0].T

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]], dtype=float32)

In [46]:
#filt = tf.random_normal([size,size,1,1], mean=0, stddev=0.1 ,seed=0, dtype=tf.int32) #[height, width, color, output_size]
filt =np.array([1.0]*(size*size*batch_size) ,dtype=np.float32).reshape([size,size,1,1])
filt.shape

(3, 3, 1, 1)

In [47]:
filt.T[0][0].T

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [54]:
h_conv = tf.nn.conv2d(img_batch, filt,strides=[2,1,1,1], padding='SAME' )

In [ ]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    h = sess.run(h_conv)

In [50]:
h.shape

(1, 3, 3, 1)

In [51]:
h[0].T[0].T

array([[  8.,  15.,  12.],
       [ 21.,  36.,  27.],
       [ 20.,  33.,  24.]], dtype=float32)

In [53]:
#padding = SAME
[
[ 0.,  0.,  0., 0.,0.],
[ 0., 0.,  1.,  2.,0.],
[ 0., 3.,  4.,  5.,0.],
[ 0., 6.,  7.,  8.,0.],
[ 0., 0.,  0.,  0.,0.]
]

[[0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 2.0, 0.0],
 [0.0, 3.0, 4.0, 5.0, 0.0],
 [0.0, 6.0, 7.0, 8.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0]]